### ISSUE TITLE
Create GUI

### ISSUE THREAD

**Issue by LightMike** [crickert1234/SparkFun-AS726X#1]
Hello,
I am a very beginner in Arduino programming and decided to go for the AS7262 as my
first sensor. Such I found your repository on GitHub.

Could you please write a short description how to make the code run.

I expect that I have to uploade the *.ino file to the Arduino (Sparkfun Blackboard in my case)
But what to do with the *.pde file?
And what about the " virtual COM drivers from FTDI".

Thanks a lot for your support.

Michael

**Comment by christianrickert** [comment]
Hi @LightMike,

Hope you're doing well!

> I expect that I have to uploade the *.ino file to the Arduino (Sparkfun Blackboard in my case)

That is correct. The easiest way is to use the [Arduino IDE](https://www.arduino.cc/en/Main/Software) for uploading the *.ino file to your SparkFun Blackborad.
SparkFun has a lot of tutorials online, including a [complete tutorial](https://learn.sparkfun.com/tutorials/installing-arduino-ide/all) explaining the use of the Arduino IDE with SparkFun hardware.

> But what to do with the *.pde file?

The *.pde file is a "Processing" file type, the Languages section next to the repository lists the programming languages used in the repository. The [Processing IDE](https://processing.org/download/) is similar to the Arduino IDE, but instead of creating sketches for Arduinos (in C/C++) you create graphical user interfaces for host systems (in the Processing language). Check the [Processing tutorials](https://processing.org/tutorials/) page, if you want to learn a bit more about the language.

In general: The Arduino sketch runs the Arduino hardware with the sensors and enables serial communication with the Processing user interface. The Processing user interface in turn visualizes the (ASCII) data received from the serial port and controls the hardware by sending data (ASCII) back to the serial port.

The virtual COM drivers from FTDI are required to let a Windows host system handle the USB connection virtually like a (hardware) serial port - it's therefore called a vitual COM port. The installation is covered in the [Windows section](https://learn.sparkfun.com/tutorials/installing-arduino-ide/all#windows) SparkFun tutorial.

Tinkering with the hardware is fun! Please let me know, if you run into issues and I'll try to get you started.

**Comment by LightMike** [comment]
Hi Christian,
things are doing well here, I hope for you, too.

Thanks for you instructions. It was quite easy after learning some basics on processing.

The only thing, which is not perfect are the values next to the sliders, which do not dissappear after
the slider has moved. Is this a matter of the controlP5 library??

Thanks again and have a nice week end.

Greetings.
Michael

![image](https://user-images.githubusercontent.com/71723869/94336795-0d5d4a00-ffe6-11ea-8866-5ddaae3d11f9.png)

**Comment by LightMike** [comment]
Hello again. 
Got it. Just have to add a background command at the end of the

void receiveSensorData() function.

Regards,
Michael

**Comment by christianrickert** [comment]
Awesome! 👍 

Usually the graphics card drivers need to be updated to support full hardware acceleration. - Without the hardware support, you'll often find rendering artifacts from visual libraries.

Have a great weekend,
Chris
